import { NextApiRequest, NextApiResponse } from 'next';

const handler = (_: NextApiRequest, res: NextApiResponse) => {
  res.status(200).json([
    {
      id: '1',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '2',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플', '가나다라마바사아자차카타파하'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '3',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: [
        '루나',
        '메이플',
        '가나다라',
        '마바사',
        '아자',
        '차',
        'ㅋ',
        'ㅏ',
      ],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '4',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '5',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '6',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '7',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '8',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '9',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '10',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '11',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '13',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '14',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '15',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '16',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '17',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '18',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
    {
      id: '19',
      title: 'MapleStory',
      contents: '루나 서버 같이 할 친구 구합니다',
      hashtag: ['루나', '메이플'],
      kakaoLink: 'https://open.kakao.com/o/gE8hl3Md',
      discordLink: 'https://discord.gg/fdx28qxX',
      latestPullUpDateTime: '1655806997364',
      memberId: '1',
      gameId: '1',
    },
  ]);
};

export default handler;
