import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Find Game Friend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>hello, world</p>
        <Link href="/about">To About</Link>
        <Link href="/component_test">To Test Layout</Link>
      </main>

      <footer>footer</footer>
    </div>
  );
};

export default Home;
