import CardLayout from '@/layout/CardLayout';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Find Game Friend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CardLayout />
      <footer>foot</footer>
    </div>
  );
};

export default Home;
